image: java:8

stages:
  - build
  - test
  - qaqc
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/CustomerAccount-0.0.1-SNAPSHOT.jar

test:
  stage: test
  script: ./mvnw test

qaqc:
  stage: qaqc
  script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push customeraccountqaqc
  only:
    - qaqc
production:
  stage: deploy
  script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push customeraccount
  only:
    - master